In [1]:
import torch

In [9]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [10]:
len(x)

12

In [11]:
x.numel()

12

In [13]:
x.shape

torch.Size([12])

In [19]:
X = x.reshape(-1, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [20]:
torch.zeros(2, 3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [22]:
torch.ones(2, 3, 4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [23]:
torch.randn(2, 3, 4)

tensor([[[-0.1809,  0.0504,  0.7816,  0.8391],
         [ 1.1549, -1.2938,  0.3808,  0.3515],
         [ 0.5609, -0.2726,  0.7983, -1.4498]],

        [[-1.5315,  1.4716,  0.8288, -1.1754],
         [ 2.5829,  0.1102, -1.2500,  0.3299],
         [-0.5422,  1.0682,  0.2108, -1.4099]]])

In [24]:
X[1,2]

tensor(6.)

In [28]:
X[1][2] - X[1,2]

tensor(0.)

In [29]:
exp_x = torch.exp(x)
exp_x

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04])

In [30]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [31]:
X.sum()

tensor(66.)

In [32]:
X.sum(dim=0)

tensor([12., 15., 18., 21.])

In [33]:
# broadcasting
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [34]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [38]:
# saving memory by in-place updates

# using a third one
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

# using [:] or += (X[:] = X + Y or X += Y)
before = id(X)
X += Y
id(X) == before

id(Z): 140408056089952
id(Z): 140408056089952


True

In [39]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [40]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)